package pl.pw.pap.akari.model.component.event;

public enum EVENT_TYPE {
    NEW_GAME_EVENT, LOAD_GAME_EVENT, SETTINGS_EVENT, QUIT_EVENT, RESUME_EVENT,

    CHANGE_CONTEXT_TO_MENU_EVENT, CHECK_GAME_EVENT, SAVE_GAME_EVENT, BOARD_BUTTON_EVENT,
    
    NEXT_EVENT, TOURNAMENT_EVENT, TOURNAMENT_GAME_EVENT
}
